sudo: required

services:
  - docker

env:
  global:
    CACHE_IMAGE: undeadops/giles

before_script:
  - docker pull $CACHE_IMAGE:build-env || true
  #- docker pull $CACHE_IMAGE:giles-latest || true

script:
  - docker build
      --target build-env
      --cache-from $CACHE_IMAGE:giles-base
      --tag $CACHE_IMAGE:giles-base
      --file ./Dockerfile
      "."
  - docker build
      --target test
      --cache-from $CACHE_IMAGE:giles-base
      --tag $CACHE_IMAGE:giles-test
      --file ./Dockerfile
      "."
  - docker build
      --target build
      --cache-from $CACHE_IMAGE:giles-base
      --tag $CACHE_IMAGE:giles-build
      --file ./Dockerfile
      "."

after_success:
  - docker build
      --target release
      --cache-from $CACHE_IMAGE:giles-build
      --tag $CACHE_IMAGE:$TRAVIS_BUILD_NUMBER
      --file ./Dockerfile
      "."
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push $CACHE_IMAGE:giles-base
  - docker push $CACHE_IMAGE:$TRAVIS_BUILD_NUMBER