apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: giles
spec:
  replicas: 1
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: giles
        tier: backend
        env: prod
    spec:
      containers:
      - name: giles
        image: undeadops/giles:test
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DEBUG
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: mongo_host
          - name: MONGO_PORT
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: mongo_port
          - name: MONGO_DBNAME
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: mongo_dbname
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: mongo_username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: mongo_password
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: giles-v1
                key: port
        readinessProbe:
          # an http probe
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
          limits:
            cpu:  1000m
            memory: 180Mi
          requests:
            cpu:  500m
            memory: 180Mi

---

apiVersion: v1
kind: Service
metadata:
  name: giles
  labels:
    app: giles
    env: prod
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: giles
    env: prod
